version: "3.6"

# https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Docker-Compose
# https://blog.ippon.tech/set-up-a-reverse-proxy-nginx-and-docker-gen-bonus-lets-encrypt/
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/environment/docker-compose.yaml

networks:
  sister:
    name: sister
  seafile-net:

  # pydio475net:
  #   name: pydio475net
  # pydionet:
  # pydio475net:
  #      external:true # this being indented from 'name: sister' just added external: true to the name sister.


services:
  #
  # web:
  #   # to test this jwilder/LE
  #   # http://web456-108-168-7-24.nip.io/
  #   # https://web456-108-168-7-24.nip.io/
  #   image: nginx:1.15-alpine
  #   # container_name: example-webapp
  #   volumes:
  #     - ./nindex.html:/usr/share/nginx/html/index.html
  #   expose:
  #     - "80"
  #   environment:
  #     - VIRTUAL_HOST=web456-108-168-7-24.nip.io
  #     - VIRTUAL_PORT=80
  #     - LETSENCRYPT_HOST=web456-108-168-7-24.nip.io
  #     - LETSENCRYPT_EMAIL=dgleba@gmail.com
  #   restart: always
  #   networks:
  #     - sister

  jproxy:
  # docker-compose pull nproxy to update...
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/nginx/certs:/etc/nginx/certs:ro
      - ./vol/nginx/html:/usr/share/nginx/html
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d:ro
      # - ./vol/nginx/conf.d:/etc/nginx/conf.d/
      - ./vol/nginx/conf.d/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    networks:
      - sister
      # - pydionet
      # - pydio475net
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  lets:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d
      - ./vol/nginx/certs:/etc/nginx/certs:rw
      - ./vol/nginx/html:/usr/share/nginx/html
    restart: always
    networks:
      - sister
      # - pydionet
      # -w pydio475net
    depends_on:
      - jproxy
    # links will share the volumes between containers.
    links:
      - jproxy
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  # seafile:
  #   # see custom config ./vol/nginx/vhost.d/sf-108-168-7-24.nip.io
  #   image: seafileltd/seafile:6.2.5
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - ../datasys/seafiledata:/shared
  #   ports:
  #     - "6311:80"
  #   expose:
  #     - "80"
  #     - "8000"
  #     - "8082"
  #   environment:
  #     # - VIRTUAL_HOST=sf-108-168-7-24.nip.io
  #     # - LETSENCRYPT_HOST=sf-108-168-7-24.nip.io
  #     # - VIRTUAL_HOST=sf-216-110-224-238.nip.io
  #     # - LETSENCRYPT_HOST=sf-216-110-224-238.nip.io
  #     #
  #     - VIRTUAL_HOST=sf.dg.jgleba.com
  #     - LETSENCRYPT_HOST=sf.dg.jgleba.com
  #     - LETSENCRYPT_EMAIL=dgleba@gmail.com
  #     - VIRTUAL_NETWORK=sister
  #     - VIRTUAL_PORT=80
  #   networks:
  #     - sister
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100k"
  #       max-file: "5"


  seafile2:
    # see custom config ./vol/nginx/vhost.d/sf-108-168-7-24.nip.io
    image: seafileltd/seafile:6.2.5
    restart: unless-stopped
    ports:
      - "6312:80"
    expose:
      - "80"
      - "8000"
      - "8082"
    env_file:
      - .env.sf2
    environment:
      - VIRTUAL_NETWORK=sister
      - VIRTUAL_PORT=80    
    volumes:
      - ../datasys/seafiledata2:/shared
    networks:
      - sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"


  # ======================================================================

  seafile3:
    image: seafileltd/seafile-mc:7.0.5
    # container_name: seafile
    restart: unless-stopped
    ports:
      - "14180:80"
      #  - "443:443"  # If https is enabled, cancel the comment.
    env_file:
      - .env.sf3
    environment:
      - VIRTUAL_NETWORK=sister
      - VIRTUAL_PORT=80
    volumes:
      - ../datasys/seafile3/sdata:/shared   
      - ./wait-for-it.sh:/a/wait-for-it.sh   
      - ./seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    depends_on:
      - db
      - memcached
    # at first startup, start db first, then seafile.
    # This needs a command after the wait I think.... command: /a/wait-for-it.sh db:3306 --timeout=34 
    networks:
      - sister
      # - seafile-net
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"


  db:
    image: mariadb:10.4
    # container_name: seafile-mysql
    restart: unless-stopped
    ports:
      - "14181:3306"
    #     - "443:443"  # If https is enabled, cancel the comment.
    env_file:
      - .env.sf3
    volumes:
      - ../datasys/seafile3/mariadb:/var/lib/mysql  
    networks:
      - sister
      # - seafile-net
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    command:
      - --bind-address=0.0.0.0
      - --default-authentication-plugin=mysql_native_password
      # --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  memcached:
    image: memcached:1.5.6
    # container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - sister
      # - seafile-net
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"


