version: "3.6"

# https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Docker-Compose
# https://blog.ippon.tech/set-up-a-reverse-proxy-nginx-and-docker-gen-bonus-lets-encrypt/
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/environment/docker-compose.yaml

networks:
  sister:
    name: sister
      external:true

services:
  # web:
  # http://web456-208-168-7-24.nip.io/
  # https://web456-208-168-7-24.nip.io/
  # image: nginx:1.15-alpine
  # # container_name: example-webapp
  # volumes:
  #   - ./nindex.html:/usr/share/nginx/html/index.html
  # expose:
  #   - "80"
  # environment:
  #   - VIRTUAL_HOST=web-104-193-61-58.nip.io
  #   - VIRTUAL_PORT=80
  #   - LETSENCRYPT_HOST=web-104-193-61-58.nip.io
  #   - LETSENCRYPT_EMAIL=d@gmail.com
  # restart: always
  # networks:
  #   - sister

  jproxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/vhost.d:/etc/nginx/vhost.d
      - ./vol/certs:/etc/nginx/certs:ro
      - ./vol/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    networks:
      - sister

  lets:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/vhost.d:/etc/nginx/vhost.d
      - ./vol/certs:/etc/nginx/certs:rw
      - ./vol/html:/usr/share/nginx/html
    restart: always
    networks:
      - sister
    depends_on:
      - jproxy
    # links will share the volumes between containers.
    links:
      - jproxy
